"""add_asset_value_update_table

Revision ID: 123371f1974d
Revises: f78b466bcf48
Create Date: 2025-03-28 17:24:16.261761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123371f1974d'
down_revision = 'f78b466bcf48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_value_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_value_update')
    # ### end Alembic commands ###
