"""add_has_market_price_and_other_columns

Revision ID: f78b466bcf48
Revises: 8e95a0173ddb
Create Date: 2025-03-28 16:47:56.888910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78b466bcf48'
down_revision = '8e95a0173ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_market_price', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('issuer', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('maturity_date', sa.Date(), nullable=True))
        batch_op.alter_column('ticker',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.alter_column('ticker',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('maturity_date')
        batch_op.drop_column('issuer')
        batch_op.drop_column('has_market_price')

    # ### end Alembic commands ###
